### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by TuyishimireEric**

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi @TuyishimireEric, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments below and under the review._

 #### I will leave the comment here, since your `Readme file` is not accessible for this PR ####
- [ ] Please kindly update your `readme file` to reflect the changes for this milestone as this will make your `readme file` more informative and professional. Checkout this [template](https://github.com/microverseinc/readme-template) and adapt it to your project. Replace all the information in the various sections of the template with information pertaining to your poject. 
- [ ] `Linters` are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practice. Your project is failing `Linter Checks`, please kindly fix the issue with `Stylelint` and `Webhint`. Please checkout the error messages, they are really explicit. One has to do with setting up the `viewport` in the header section of your html file and the other has to do with leaving empty lines. 
- [ ] Please kindly add a descriptive pull request `title` talking the changes inside and a pull request `summary`, describing introduced changes in more detail. Checkout the second point in this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for clarifications. 
- [ ] In your next projects, please use imperative tense in your commit messages, capitalizing the first letter of each sentence. Make sure your commit messages are meaningful. Checkout the third point in this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for clarifications

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TuyishimireEric** [comment]
I have made the required changes to this project.

**Comment by omar-labana** [comment]
# **Approved ✔️**

Hi @TuyishimireEric

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TuyishimireEric** [comment]
Thank you so much

I failed a lot to complete my first project but now I have understood!!

**Pull request merged**
